get_new: false
kind_imputer: iterative
model_name: gridgbm_1000000_iterative_False
model_type: lightgrid
nrows_test: 100000
nrows_train: 1000000
only_quantitative: false
qualitative_cols:
- date
- is_enabled
- items_first_enabled_date
- store_first_saving_date
- store_last_saving_date
- pickup_start
- pickup_end
quantitative_cols:
- total_supply
- declared_supply
- manual_added_supply
- manual_removed_supply
- meals_saved
- consumer_cancellation
- store_cancellation
- item_price
- meals_refunded
- rating_count
- sum_rating_overall
sample_name: dummy_sample
target_encoding: true