nrows_train: 1000
nrows_test: 10
split_ratio: 0.5
model_name: dummy
sample_name: dummy_sample
model_type: rfc
get_new: False
only_quantitative: True
target_encoding: False
kind_imputer: iterative
qualitative_cols:
  - 'total_supply'
  - 'declared_supply'
  - 'manual_added_supply'
  - 'manual_removed_supply'
  - 'meals_saved'
  - 'consumer_cancellation'
  - 'store_cancellation'
  - 'item_price'
  - 'meals_refunded'
  - 'rating_count'
  - 'sum_rating_overall'
