get_new: false
kind_imputer: iterative
model_name: dummy
model_type: logit
nrows_test: 10
nrows_train: 1000
only_quantitative: true
qualitative_cols: &id001 !!python/object:dynamic_yaml.yaml_wrappers.YamlList
  _collection:
  - total_supply
  - declared_supply
  - manual_added_supply
  - manual_removed_supply
  - meals_saved
  - consumer_cancellation
  - store_cancellation
  - item_price
  - meals_refunded
  - rating_count
  - sum_rating_overall
  _recursive: false
  _regx: &id002 !!python/object/apply:re._compile
  - .*{.*}.*
  - 32
  _root: &id003 !!python/object:dynamic_yaml.yaml_wrappers.YamlDict
    _collection:
      get_new: false
      kind_imputer: iterative
      model_name: dummy
      model_type: logit
      nrows_test: 10
      nrows_train: 1000
      only_quantitative: true
      qualitative_cols: *id001
      sample_name: dummy_sample
      split_ratio: 0.5
      target_encoding: false
    _recursive: false
    _regx: *id002
    _root: *id003
sample_name: dummy_sample
split_ratio: 0.5
target_encoding: false
